### ISSUE TITLE
Pypi package is incomplete (cannot install stack via pip)

### ISSUE THREAD

**Issue by monkpit** [RyanKung/stack#2]
Installing this package via pip does not work because `VERSION` cannot be found.

The reason it can't be found is because it doesn't exist :)

`pip3 install --download="./python-stack-pypi/" python-stack`
`cd python-stack-pypi`
`tar -xvf python-stack-0.1.3.1.tar.gz`
`cd python-stack-0.1.3.1`
`ls`

No VERSION to be found! :(

**Comment by RyanKung** [comment]
Yeah, I forgot to add the `MAINFEST.in` file, (and will be add to the next version). Thanks for response this bug.
